# Generated by Django 4.0.6 on 2022-07-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_setting_delete_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
